language: shell
sudo: false
script:
 - bash -c 'shopt -s globstar; shellcheck strapped.sh'
 - bash -c 'shopt -s globstar; shellcheck straps/**/*.sh'
 - bash -c 'shopt -s globstar; shellcheck build/*.sh'
matrix:
  fast_finish: true